<html>
<head>
    <title>Try Catch finally</title>
</head>
<body>
    <script>
        // console.log("log 메시지");
        // console.log("안녕하세요?");

        try {
            console.log("log 메시지");
        } catch(err) {
            console.log(err.name);
            console.log(err.message);
        }
        
        console.log("안녕하세요?");


        //throw를 사용하여 강제로 예외를 발생시킴
        var x = "";

        try {
            if(x === "") throw "empty"
            var y = x + 3;
            console.log(y);
        } catch(error){
            consol.log('x, is $(err0r)');
        } finally {
            consol.log("exception 유무와 상관 없이 무조건 실행됨");
        }

    </script>
</body>
</html>